import type { Metadata } from 'next';
import './globals.css';
import ReduxLayout from './components/ReduxLayout/ReduxLayout';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang='en'>
			<body>
				<ReduxLayout>
					<main className='main-container'>{children}</main>
				</ReduxLayout>
			</body>
		</html>
	);
}
