import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from './components/Header/Header';
import ReduxLayout from './components/ReduxLayout/ReduxLayout';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang='en'>
			<body>
				<ReduxLayout>
					<Header />
					{children}
				</ReduxLayout>
			</body>
		</html>
	);
}
