"""empty message

Revision ID: 39453fe2b3bc
Revises: dfe0a3ced52b
Create Date: 2026-01-28 23:33:21.696032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39453fe2b3bc'
down_revision = 'dfe0a3ced52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('sec_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sec_name', sa.VARCHAR(length=80), nullable=True))

    # ### end Alembic commands ###
