"""empty message

Revision ID: 015fb305985e
Revises: 86fc02189d5d
Create Date: 2026-02-10 15:10:39.970469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015fb305985e'
down_revision = '86fc02189d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
