"""empty message

Revision ID: 064dba756e2d
Revises: ca466f2941e8
Create Date: 2026-02-13 23:01:22.560686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064dba756e2d'
down_revision = 'ca466f2941e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
