"""empty message

Revision ID: 0f7821ead070
Revises: 90313bff2b9f
Create Date: 2026-02-11 21:48:57.972853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7821ead070'
down_revision = '90313bff2b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_dishes',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('meal_id', 'dish_id')
    )
    op.drop_table('meal_ingredients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_ingredients',
    sa.Column('meal_id', sa.INTEGER(), nullable=False),
    sa.Column('dish_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('meal_id', 'dish_id')
    )
    op.drop_table('meal_dishes')
    # ### end Alembic commands ###
