"""empty message

Revision ID: 18cc8827df4e
Revises: 
Create Date: 2026-02-14 18:11:49.109222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cc8827df4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals_dishes',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('meal_id', 'dish_id')
    )
    op.drop_table('meal_dishes')
    op.drop_table('orders_meals')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_given', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_type', sa.String(length=20), nullable=False))
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.create_foreign_key("fk_orders_meal_id_meals", 'meals', ['meal_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('patronymic',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('patronymic',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.drop_column('payment_type')
        batch_op.drop_column('is_given')
        batch_op.drop_column('price')
        batch_op.drop_column('meal_id')

    op.create_table('orders_meals',
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('meal_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'meal_id')
    )
    op.create_table('meal_dishes',
    sa.Column('meal_id', sa.INTEGER(), nullable=False),
    sa.Column('dish_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('meal_id', 'dish_id')
    )
    op.drop_table('meals_dishes')
    # ### end Alembic commands ###
