"""empty message

Revision ID: 23577a863805
Revises: 874b6d2b4791
Create Date: 2026-02-09 11:09:10.052089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23577a863805'
down_revision = '874b6d2b4791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.alter_column('day_of_weak',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.alter_column('day_of_weak',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
