"""empty message

Revision ID: 3fefeb77a012
Revises: 5ed895aeb11b
Create Date: 2026-02-09 20:36:38.351637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fefeb77a012'
down_revision = '5ed895aeb11b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.alter_column('is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.alter_column('is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
