"""empty message

Revision ID: 40193edc9b4d
Revises: 5dceeaa3a705
Create Date: 2026-02-09 12:58:25.762766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40193edc9b4d'
down_revision = '5dceeaa3a705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
