"""empty message

Revision ID: 48ae280f7a14
Revises: 3fefeb77a012
Create Date: 2026-02-10 14:46:48.944384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ae280f7a14'
down_revision = '3fefeb77a012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish_ingredient', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
