"""empty message

Revision ID: 56735df0b430
Revises: 40193edc9b4d
Create Date: 2026-02-09 15:23:05.683771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56735df0b430'
down_revision = '40193edc9b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_dishes')
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))

    op.create_table('_alembic_tmp_dishes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('weight', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
