"""empty message

Revision ID: 62508330f01a
Revises: 
Create Date: 2026-02-02 15:30:47.368201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62508330f01a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('patronymic', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('balance', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('balance')
        batch_op.drop_column('patronymic')
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
