"""empty message

Revision ID: 69df066f5976
Revises: 62508330f01a
Create Date: 2026-02-02 15:31:21.359378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69df066f5976'
down_revision = '62508330f01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('patronymic',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('patronymic',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###
