"""empty message

Revision ID: 74453482bc30
Revises: 
Create Date: 2026-02-13 01:35:13.932813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74453482bc30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_meals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_meals',
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('meal_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'meal_id')
    )
    # ### end Alembic commands ###
