"""empty message

Revision ID: 749d61992c1a
Revises: 1c6ff2b28b66
Create Date: 2026-02-16 15:01:36.425433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749d61992c1a'
down_revision = '1c6ff2b28b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
