"""empty message

Revision ID: 874b6d2b4791
Revises: ae13e078ea33
Create Date: 2026-02-09 11:08:11.130725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874b6d2b4791'
down_revision = 'ae13e078ea33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_meals')
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_weak', sa.String(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))
        batch_op.drop_column('day_of_weak')

    op.create_table('_alembic_tmp_meals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day_of_weak', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
