"""empty message

Revision ID: 8e1720c6828e
Revises: 
Create Date: 2026-02-01 14:32:45.772649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8e1720c6828e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_column('meal')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('characteristics')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characteristics', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
