"""empty message

Revision ID: 90313bff2b9f
Revises: 015fb305985e
Create Date: 2026-02-10 15:11:26.636715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90313bff2b9f'
down_revision = '015fb305985e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
