"""empty message

Revision ID: ca466f2941e8
Revises: c4b84df5a776
Create Date: 2026-02-13 22:36:06.732544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca466f2941e8'
down_revision = 'c4b84df5a776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('is_given',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('is_given',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
