"""empty message

Revision ID: d04ee7166931
Revises: 
Create Date: 2026-02-09 17:22:46.800237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04ee7166931'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        # Создаём НОВЫЙ внешний ключ с явным именем
        batch_op.create_foreign_key(
            'fk_purchase_requests_user_id',  # ← уникальное имя
            'users',
            ['user_id'],
            ['id']
        )
        # Удаляем старый столбец — внешний ключ к нему исчезнет автоматически
        batch_op.drop_column('cook_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cook_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['cook_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
