"""empty message

Revision ID: fa08d3fdce04
Revises: ad0058089762
Create Date: 2026-02-13 23:03:49.961107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa08d3fdce04'
down_revision = 'ad0058089762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.String(length=20), nullable=True))
        batch_op.alter_column('is_given',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('is_given',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###
